! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : model_JacobianSP.f90
! Time                 : Sun Feb  5 00:06:35 2017
! Working directory    : /work/home/dp626/DSMACC2
! Equation file        : model.kpp
! Output root filename : model
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE model_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(10) :: LU_IROW = (/ &
       1,  2,  3,  3,  3,  4,  4,  5,  5,  5 /)

  INTEGER, PARAMETER, DIMENSION(10) :: LU_ICOL = (/ &
       1,  2,  1,  2,  3,  2,  4,  1,  3,  5 /)

  INTEGER, PARAMETER, DIMENSION(6) :: LU_CROW = (/ &
       1,  2,  3,  6,  8, 11 /)

  INTEGER, PARAMETER, DIMENSION(6) :: LU_DIAG = (/ &
       1,  2,  5,  7, 10, 11 /)


END MODULE model_JacobianSP

